Added/fixed extract. fields and opt. search func
adrianRoman24/Monitoring-System-Randomization pull request #2
Opened 2023-04-24 15:35 UTC by catalinduta613

2023-04-24 16:22 UTC, adrianRoman24 requested changes

2023-04-24 16:22 UTC, adrianRoman24 commented on Sniffer/main.py
> +        epoch_start = epoch_minutes_ago.strftime("%H:%M")
not needed

2023-04-24 16:22 UTC, adrianRoman24 commented on Sniffer/main.py
> +                "epoch_start": epoch_start
i updated it to be stored here https://github.com/adrianRoman24/Monitoring-System-Randomization/blob/main/Sniffer/main.py#L124, so we use storage efficiently

2023-04-24 16:22 UTC, adrianRoman24 commented on Sniffer/main.py
> +        log("channel: " + str(channel))
use logging + debug

2023-04-24 16:22 UTC, adrianRoman24 commented on Sniffer/main.py
> +mac_to_index = {item["mac"]: i for i, item in enumerate(epoch_list)}
this is not correct, right? it is updated only once, when the program is started. You should just keep a dictionary with the mac addresses present in current epoch, when the epoch ends, reset the dictionary.

2023-04-24 16:22 UTC, adrianRoman24 commented on Sniffer/main.py
> +        epoch_minutes_ago = now - datetime.timedelta(minutes=EPOCH_LENGTH_IN_MIN)
EPOCH_LENGTH_IN_MIN does not exist anymore, use config. Did you even test the code?

2023-04-24 18:44 UTC, adrianRoman24 requested changes

2023-04-24 18:44 UTC, adrianRoman24 commented on Sniffer/main.py
> +            ext_rates = [int(rate * 0.5) for rate in ext_rates_raw]
this variable is defined only when ext_rates_ie is not null, not ok

2023-04-24 18:44 UTC, adrianRoman24 commented on Sniffer/main.py
> +                "ext_rates": ext_rates,
this line throws error when the variable is not defined

2023-04-24 18:44 UTC, adrianRoman24 commented on Sniffer/main.py
> +            supported_rates = [int((rate) * 0.5) for rate in supported_rates_raw]
what do the rates represent, what unit measure is this?

2023-04-24 18:44 UTC, adrianRoman24 commented on Sniffer/main.py
> +    if mac in epoch_mac_dict:
you can use .get(..., None) method here, it is more efficient

2023-04-24 20:00 UTC, catalinduta613 commented on Sniffer/main.py
> +            supported_rates = [int((rate) * 0.5) for rate in supported_rates_raw]
"When the supported rates field is parsed from the packet, Scapy automatically maps the raw values to their corresponding human-readable representation. For example, the raw value of 2 corresponds to 1.0 Mbps, 4 corresponds to 2.0 Mbps, and so on. This mapping is based on the 802.11 standard, which defines the mapping between raw values and corresponding data rates."
So the values stored are in Mbps

2023-05-03 14:21 UTC, adrianRoman24 approved these changes
LGTM!

2023-05-03 14:21 UTC, merged